### ISSUE TITLE
Doe's it have MiT license?

### ISSUE THREAD

**Issue by zbeedatm** [kzrfaisal/angular-file-uploader#1]
I want to use your component but couldn't find any licensing!

**Comment by kzrfaisal** [comment]
Right now it does not have any license, you can use it.

**Comment by zbeedatm** [comment]
I need MIT or apache license in order to be able to use it in our company : S
Thanks anyway.

**Comment by kzrfaisal** [comment]
Anyway I was going to add MIT Licence.
Just wait for few minutes

**Comment by kzrfaisal** [comment]
OK MIT License added....
Maybe Now you can use it
