### ISSUE TITLE
It is only uploading the second file

### ISSUE THREAD

**Issue by amt123** [kzrfaisal/angular-file-uploader#10]
Hello,

I'm trying to upload multiple files  at the  same time but it is taking only second file.
 I'm using latest angular version 6 and spring boot for back end.

![image](https://user-images.githubusercontent.com/15020172/43129811-df57db86-8f3d-11e8-96cf-068653040821.png)
![image](https://user-images.githubusercontent.com/15020172/43129893-0c1e07b2-8f3e-11e8-9f07-5b23f64c672c.png)

**Comment by kzrfaisal** [comment]
Can you share your afuConfig Object.
