### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Template parse errors:

### ISSUE THREAD

**Issue by abdelabdelboufbouf123** [kzrfaisal/angular-file-uploader#100]
When i follow the readMe file i'm confronted with this error :   ```
Can't bind to 'disabled' since it isn't a known property of 'label'. (" btn-sm afu-select-btn" [ngClass]="progressBarShow ? 'disabled' : null"

    *ngIf="!hideSelectBtn" [ERROR ->][disabled]="progressBarShow">{{replaceTexts?.selectFileBtn}}</label>

  <input type="file" id="sel{{i"): ng:///AngularFileUploaderModule/AngularFileUploaderComponent.html@15:27
```

**Comment by kzrfaisal** [comment]
May I know the browser you were using when this occurred?

**Comment by kzrfaisal** [comment]
Anyway Issue has been resolved in the latest 7.1.1 version.
@abdelabdelboufbouf123  Thanks for pointing out the issue.
