### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by salehasadi** [kzrfaisal/angular-file-uploader#15]
hi,
first things first, thank you for this good module.

how can i change the strings and styles of this module!?

**Comment by kzrfaisal** [comment]
Hi @salehasadi ,
First of all, thanks for the appreciation.
Right now , out of the box, any option is not given for that.
But you can overwrite the styles and strings.
check it out here: https://github.com/kzrfaisal/angular-file-uploader/blob/master/projects/angular-file-uploader/src/lib/angular-file-uploader.component.ts

**Comment by kzrfaisal** [comment]
you can expect these functionalities in coming updates

**Comment by salehasadi** [comment]
Thank you
