### ISSUE TITLE
Not able to handle exceptions

### ISSUE THREAD

**Issue by deshpandecounsultants** [kzrfaisal/angular-file-uploader#16]
Hi
We are using angular-file-uploader (Ver. 4.1.2). I’ve set up config for the same and in the config I’ve set formatsAllowed = .xls, .xlsx. But when user selects All Files option on Open Dialog and selects file with unwanted extension though it is not throwing an exception but we need some way to handle such scenario, so that, we can show proper message to user.

Component URL: https://www.npmjs.com/package/angular-file-uploader (https://www.npmjs.com/package/angular-file-uploader)
Thank you!

Kind regards,
Madan Deshpande PMP® ITIL

**Comment by kzrfaisal** [comment]
Exception handling is present there.
Can you share your config object

**Comment by deshpandecounsultants** [comment]
Below are the details. I’m assigning following object to [Config]

URLConfig = {
       multiple: false,
       formatsAllowed: “.xls, .xlsx”,
       theme: “attachPin”,
       attachPinText: “ ”,
       uploadAPI: {
                     url: ‘<url>’,
                     header: ‘<token header>’
    }
};

Please let me know if you need more information.

Thank you!
Madan

**Comment by kzrfaisal** [comment]
Hi @deshpandecounsultants,
Thanks for providing the info.
Every theme is developed for a different purpose, and you are using attachPin theme, which is focussed on displaying minimum possible elements, so if the format is invalid, then that file will be rejected under the hood and will not be displayed. For user satisfaction, you can provide a small note around the plugin. However, if you want to display invalid files also, you can use the default theme.
