### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by neoswf** [kzrfaisal/angular-file-uploader#17]
Awesome work! Love the component! 
Question: how can I translate the component? My app is in Brasilian-Portuguese. Whats my best option, besides forking this project and translating it?

Thank you!

**Comment by kzrfaisal** [comment]
Hi @neoswf ,
Thanks for your words,
Right now, out of the box, any translation functionality is not provided.
Forking is the only option left.

**Comment by neoswf** [comment]
Hey @kzrfaisal. I have taken your suggestion and forked the project. 
As I see it, the only way I can use my modifications is to modify locally and build the project to include it locally inside my project. Thing is that when I run `ng run build`, the output folder is different than the one in the `node_modules` folder.

What am I suppose to do in able to get the same output? Thanks!

**Comment by kzrfaisal** [comment]
This repository has two project one is the demo app another one is angular-file-uploader(which u need), which is located inside projects.
So use 'ng build angular-file-uploader' to get its build in dist folder.
