### ISSUE TITLE
Http Headers inclusion via Http Interceptor

### ISSUE THREAD

**Issue by moro91** [kzrfaisal/angular-file-uploader#18]
I'm trying to send a POST file request but no authorization header is appended to the request. I'm using HttpInterceptors, are they supported or your component's POST call?

**Comment by kzrfaisal** [comment]
can u share your afuConfig Object.

**Comment by moro91** [comment]
`  afuConfig = {
    uploadAPI:
    {
      url: environment.fileServiceControllerBaseUrl + '/Upload'
    },
    theme: 'attachPin',
    attachPinText: 'Upload document...'
};`

**Comment by kzrfaisal** [comment]
http interceptors are not supported for now
