### ISSUE TITLE
Problems with authorization headers

### ISSUE THREAD

**Issue by romn-20** [kzrfaisal/angular-file-uploader#20]
Hi, When I send the request with: 
afuConfig = {
		uploadAPI:  {
			url: 'https://xxxxxxxxxxx/xxxxxxxxxxx/storedFile/',
			headers: {
				"Content-Type" : "multipart/form-data; ",
				"Authorization" : localStorage.getItem('authorization')
			}
		  },
		multiple: true,
		maxSize: "1",
		theme: "dragNDrop"
	};
the URL is ok but it get me a bad response (No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 400).
What I can do?

**Comment by kzrfaisal** [comment]
This problems is from API url side, please verify what type of request your API is expecting and then check whether it's recieving those expected params.
However here , your error is related to cross origin issues.
Allow your API for different origins also.
You can also solve this issue with Angular proxy-config.

**Comment by romn-20** [comment]
it is a POST request... the API service wait the uploaded file, but I
cannot get there with it.
