### ISSUE TITLE
page doesn't load OR becomes blank

### ISSUE THREAD

**Issue by chiragbhagat** [kzrfaisal/angular-file-uploader#22]
When I add the following tag in my page, the page doesn't load OR becomes blank.

<angular-file-uploader #fileUpload1
        [config]="afuConfig" 
        [resetUpload]=resetVar
        (ApiResponse)="DocUpload($event)">
    </angular-file-uploader>

What am I missing? Or can you provide complete sample implementation of a page?

**Comment by kzrfaisal** [comment]
Complete implementation is provided in the repo itself.

**Comment by chiragbhagat** [comment]
If you are pointing to ReadMe, “NO” the steps are not working. May be something is missing.

If you are pointing to code, may I know specific file/location where sample implementation is?

If you are pointing to something else, pls provide details. 

Thanks for the prompt response!

**Comment by kzrfaisal** [comment]
app.component implements it.
Link: https://github.com/kzrfaisal/angular-file-uploader/tree/master/src/app
