### ISSUE TITLE
Drap and Drop, also support for select file functionality

### ISSUE THREAD

**Issue by naveendb92** [kzrfaisal/angular-file-uploader#25]
Hello,

For the example 2, **Drap and Drop** can we also get on click event ? i.e., **Select File functionality**.

Normally the user wants either to select file / drag & drop.

if this can be combined in example 2, it would be great.

**Comment by kzrfaisal** [comment]
Hey @naveendb92 ,
In 'afuConfig' object make hide buttons property as false.
.... 
    hideProgressBar: false,
    hideResetBtn: false,
    hideSelectBtn: false
};

Customise it according to your requirements.
