### ISSUE TITLE
'Select File' does not work in IE 11

### ISSUE THREAD

**Issue by sublime392** [kzrfaisal/angular-file-uploader#27]
I know nobody cares about IE anymore, but I have to support it. Drag an drop seems to work. Using the select button allows you to choose a file, but it doesn't get listed in the selected files.

**Comment by guirkgumbo** [comment]
Are there any errors being thrown? Might be a polyfill you need to use.

**Comment by Richky** [comment]
Same thing happening to me. There is no error, the file just doesn't get added to the list of selected files. I have imported all the suggested polyfills plus a formdata-polyfill. Any idea what other polyfills might be required?

**Comment by jmsfontes** [comment]
Hello. Is there any developments on this issue? Thanks.

**Comment by narindersingh07** [comment]
Any luck on this one ? I am facing same issue, Files are not getting selected in IE

**Comment by kzrfaisal** [comment]
Well, there are no plans to support IE.
