### ISSUE TITLE
defineInjectable Not found

### ISSUE THREAD

**Issue by Guyr989** [kzrfaisal/angular-file-uploader#28]
Hey.
How are you?
My name is Guy and I tried to implement your upload-file plugin in a project of mine.
Implementing It on an empty project was easy and worked beautifully but when I plugged it into a working project this message popped up:  

WARNING in ./node_modules/angular-file-uploader/fesm5/angular-file-uploader.js
24:66-82 "export 'defineInjectable' was not found in '@angular/core'

And my app crushed. 
I have an ng5 project.

The 'defineInjectable' does exists.
And the dependencies also is up to date.
Do you have any idea what could have went wrong? 
Maybe it's a versioning issue?

Hope to hear from you soon.

Best regards,
Guy Reshef

**Comment by guirkgumbo** [comment]
Also having this issue on an existing project that I just started a couple days ago.

**Comment by vbankov** [comment]
I faced that issue as well, `defineInjectable` seems to be available in angular versions 6.x.x. If you are using angular 5, installing with `npm i angular-file-uploader@4.0.0` seems to do the trick

**Comment by guirkgumbo** [comment]
Can confirm that this issue if for angular versions < 6. Working just fine in my Angular 7 project.
