### ISSUE TITLE
Customise height and width of drag and drop window

### ISSUE THREAD

**Issue by anuj9196** [kzrfaisal/angular-file-uploader#29]
![selection_046](https://user-images.githubusercontent.com/6560085/47769416-d56a0100-dd01-11e8-9feb-3a2a3fc7057b.png)

How can I resize the `drag-and-drop` window size to fit `col-md-12` (complete page)? Also, how can I change the text **Drag N Drop**?

**Comment by kzrfaisal** [comment]
Hi Anuj,
All the details have been given in styling section of readme file. You can the class provided for drag n drop box.
