### ISSUE TITLE
Config changes are not being detected

### ISSUE THREAD

**Issue by devna13** [kzrfaisal/angular-file-uploader#30]
changes to **config.uploadAPI.headers** is not being detected and angular file upload uses old/initial auth header.

angular-file-uploader/projects/angular-file-uploader/src/lib/angular-file-uploader.component.ts  line 50
never gets fired when config gets updated with new values:

also not sure why in ngOnChanges  this.config is being used instead of rst["config"] ?

```

ngOnChanges(rst: SimpleChanges) {
    if (rst["config"]) {
....

```

`
 <angular-file-uploader #fileUpload1 [config]="config" (ApiResponse)="uploadResponse($event)"></angular-file-uploader>`

I've also tried object assign and reinitializing config but ngOnChanges is not being fired  
any suggestions?

Thanks

**Comment by kzrfaisal** [comment]
Switching to latest version may resolve this issue.
