### ISSUE TITLE
File parameter name

### ISSUE THREAD

**Issue by yglodt** [kzrfaisal/angular-file-uploader#31]
I noticed that if I upload multiple files, they are named "file0", "file1" etc:

> -----------------------------5936291719523
> Content-Disposition: form-data; name="file0"; filename="a2.txt"
> Content-Type: text/plain
> 
> 22222
> -----------------------------5936291719523
> Content-Disposition: form-data; name="file1"; filename="a1.txt"
> Content-Type: text/plain
> 
> 11111
> -----------------------------5936291719523--

In the Spring Controller I would like to receive the files as array, which does not work since they have all different names.

Can you tell me how I can have all the files just be named "file" ?

**Comment by damianchoc** [comment]
i have the same problem :(

**Comment by sadeghhp** [comment]
same :(

**Comment by BruneXX** [comment]
Hi, Is this repo currently maintained?

**Comment by kzrfaisal** [comment]
Added a config option 'fileNameIndex', set it to false to get the same name.
