### ISSUE TITLE
Change the text from Drag N Drop

### ISSUE THREAD

**Issue by ipv6wiz** [kzrfaisal/angular-file-uploader#35]
This should be fairly straightforward and work in the same way that the attachPinText config parameter works.

**Comment by kzrfaisal** [comment]
Hi @ipv6wiz  ,
You can modify labels in 'replaceTexts' attribute of your config option.
This feature is being added to the latest release.
Upgrade your module to 5.0.0+

**Comment by candorthor** [comment]
@kzrfaisal ,

I wanted to add those text in html. Replace text is in the ts file, but I wanted those in the html file.

And  wanted it to look like below.
![image](https://user-images.githubusercontent.com/49184671/67921399-8f25d700-fbcd-11e9-8d58-0512008ef928.png)

Could you please help me in this.
