### ISSUE TITLE
configuration object issue - replaceTexts

### ISSUE THREAD

**Issue by artyomv14** [kzrfaisal/angular-file-uploader#42]
Hi, I have been trying to reassign the default values in 'replaceTexts' object in angular-file-uploader@4.1.4, but the changes are not being detected at all.
Furthermore, when trying to use the latest version, the module is not being recognized at all, i.e. I cannot import the { AngularFileUploaderModule } from 'angular-file-uploader'

**Comment by kzrfaisal** [comment]
Hi @artyomv14 ,
In version 4.1.4, replace text property is not there, it's in the latest version.
In 4.1.4, you can use 'attachPinText' and 'uploadBtnText' property.
However, I'll look into module not being recognised issue.

**Comment by kzrfaisal** [comment]
I'll update the readme soon.

**Comment by artyomv14** [comment]
Thank you for being so responsive. I have tested the 5.0.2 version and now it works fine.
