### ISSUE TITLE
withCredentials param for session cookie support 

### ISSUE THREAD

**Issue by lunanigra** [kzrfaisal/angular-file-uploader#44]
Hello, would it be possible to support the param withCredentials during file upload process?

This is necessary if the server used session cookies (ok, maybe session cookies are old school; but however).

On regular HTTP call you can set this parameter additional to the headers params.
https://angular.io/api/http/RequestOptions

Thanks!

**Comment by lunanigra** [comment]
Hi, would be cool if you could update your lib.

Modification should be simple. Just add... `xhr.withCredentials = true;`

fesm5/angular-file-uploader.js, line 238 ff.
```
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;
```

Or to avoid any side effects better make this line configurable via additional parameter.

**Comment by MarrsAttax** [comment]
This gets my vote too

**Comment by pyummm** [comment]
Feature still actually required

**Comment by kzrfaisal** [comment]
noted, will be available in the next release

**Comment by kzrfaisal** [comment]
Added in version `7.1.0`
