### ISSUE TITLE
Unexpected value 'FileUploadModule' imported by the module 'AppModuleShared'. Please add a @NgModule annotation  

### ISSUE THREAD

**Issue by vinaysimharaju** [kzrfaisal/angular-file-uploader#5]
I am trying this package with angular 5. but I am getting Unexpected value 'FileUploadModule' imported by the module 'AppModuleShared'. Please add a @NgModule annotation .

Kindly suggest how can this issue be resolved

**Comment by vadal** [comment]
I have the same issue. Can anyone recommend a solution?

**Comment by Olha** [comment]
I moved to a lower version 4.0.5 and everything started to work

**Comment by Qarun-Qadir-Bissoondial** [comment]
I have moved over to version 4.0.5 and now, Angular is telling me that <angular-file-uploader> is not a known element
![image](https://user-images.githubusercontent.com/15520929/41302212-4bc62896-6e40-11e8-97e2-3fd44571ff4e.png)

**Comment by ranovladimir** [comment]
4.0.5 works fine for me

**Comment by ranovladimir** [comment]
it happened to me once. Import the FileUploadModule in the
component.module.ts that you want to use and try again. Don't put it in the
AppModule.
ᐧ

 Cordialement,

RANO Vladimir
06.50.33.76.09



2018-06-12 17:59 GMT+02:00 Qarun Qadir Bissoondial <notifications@github.com

**Comment by beshad** [comment]
i have the same issue, so this is not compatible with Angular 5?
