### ISSUE TITLE
Suggestion: directly upload on select

### ISSUE THREAD

**Issue by Codelessandro** [kzrfaisal/angular-file-uploader#50]
Hi there,

love your package.

I did some user testing and some folks don't click on the upload Button after selecting a file. It would be cool to have this as an option. Or an output event onFileSelect and an input to upload files.

What do you think?

cheers

**Comment by mustafamg** [comment]
I agree with you, the tool is great, however, this is a stopper issue for me from using it.

**Comment by gedkul** [comment]
Use  theme: "attachPin" in config and then will be automatic uploading after selecting file.

**Comment by pgrmCreate** [comment]
> Use theme: "attachPin" in config and then will be automatic uploading after selecting file.

True, "attachPin" is right but if we can't use drag&drop system with the theme "dragNDrop".

We can't use both ? Has anyone found an a hack (before next update) ?

**Comment by kzrfaisal** [comment]
`autoUpload` option and `fileSelected` event has been added  in version `7.1.0`
