### ISSUE TITLE
How do I replace the 'Invalid format' text for invalid file format?

### ISSUE THREAD

**Issue by Carlosps** [kzrfaisal/angular-file-uploader#52]
As mentioned in the README it is possible to replace some texts like (selectFileBtn, resetBtn...). Unfortunately, I was not able to replace the 'Invalid format' text in case we attach an invalid file format.

How can I do that?

Thank you.

**Comment by kzrfaisal** [comment]
Hey there,
As of now 'Invalid format' text can't be replaced.

**Comment by Carlosps** [comment]
Ok, thank you for your response.
