### ISSUE TITLE
How to hide buttons while uploading

### ISSUE THREAD

**Issue by snblackout** [kzrfaisal/angular-file-uploader#54]
Hello,

Can someone point me in the correct direction of documentation that explains how to hide the "Select File", "Reset" and "Upload" buttons and also get percentage value as uploading to change custom progress bar when the data transfer is happening?  I can only see `(ApiResponse)="fileUploaded($event)"` as an event after the API returns.

Thank you.

**Comment by kzrfaisal** [comment]
Hi,
For Modifying the CSS part, classes are provided for every major element.
And currently, there no event handler provided for tracking the progress.
