### ISSUE TITLE
Display Image before Upload

### ISSUE THREAD

**Issue by Monchai** [kzrfaisal/angular-file-uploader#56]
how can i catch the event after file selection for display file before press upload button ?

**Comment by netzonjonathan** [comment]
Hi,

This is what I did for image files.

`<img src="{{ previewSrc }}">`

`<angular-file-uploader [config]="afuConfig" #avatar (change)=fileChange(avatar.selectedFiles)>            </angular-file-uploader>`

```
fileChange(files) {

        const file = files[0];

        const reader = new FileReader();
        reader.onload = e => this.previewSrc = reader.result;

        reader.readAsDataURL(file);    
}
```

**Comment by developerabhishek1402** [comment]
Hi, I tried the above code. But seems like the function is not getting called when I upload or drag and drop the image. Any help?

.html file

<angular-file-uploader [config]="emailConfig" [resetUpload]=resetVar (ApiResponse)="emailConfigImageUpload($event)" #avatar (change)=fileChange(avatar.selectedFiles)></angular-file-uploader>
<img src="{{ previewSrc }}">

.ts file

fileChange(files) {
    console.log('inside');
    
    const file = files[0];

    const reader = new FileReader();
    reader.onload = e => this.previewSrc = reader.result;

    reader.readAsDataURL(file);    
}
