### ISSUE TITLE
unknow defineInjectable

### ISSUE THREAD

**Issue by mahivitsit** [kzrfaisal/angular-file-uploader#6]
I'm using angular 5.2, showing error as unknow defineInjectable in angular core.
Working fine when I have changed to defineInjectable to Injectable.
please update the same in npm repo in angular-file-uploader/fesm5/angular-file-uploader.js

in line number 1: 
import { Injectable, NgModule, defineInjectable, EventEmitter, Component, Input, Output } from '@angular/core'; should be import { Injectable, NgModule, Injectable, EventEmitter, Component, Input, Output } from '@angular/core';

in line number 19: 

'AngularFileUploaderService.ngInjectableDef = defineInjectable({ factory: function'  Should be
/** @nocollapse */ AngularFileUploaderService.ngInjectableDef = Injectable({ factory: function

**Comment by taraman** [comment]
I have the same issue, it seems that it works with angular 6

**Comment by kzrfaisal** [comment]
Thanks guys for reporting it, it's fixed in the latest version i.e 4.1.2.
