### ISSUE TITLE
could you please create 5.0.2 tag?

### ISSUE THREAD

**Issue by daqingshu** [kzrfaisal/angular-file-uploader#60]
I see the version is on https://www.npmjs.com/package/angular-file-uploader/v/5.0.2, but the source code has not the tag.
I found the commit id e425a10ac2cce5faed9ae3723bd94aed5ef04853 is the 5.0.2

**Comment by kzrfaisal** [comment]
I know it's super late, but it's done now.

**Comment by daqingshu** [comment]
> I know it's super late, but it's done now.

thank you very much. ：）
