### ISSUE TITLE
Regarding the text 

### ISSUE THREAD

**Issue by candorthor** [kzrfaisal/angular-file-uploader#62]
I wanted the 'Drag N Drop' text to be replaced by below
![image](https://user-images.githubusercontent.com/49184671/67921470-d318dc00-fbcd-11e9-884f-8c3ea88ae993.png).

And I wanted it in the HTML file. so whatever the labels in 'replaceTexts' are in TS file, but I wanted it in HTML file.

Could you please let me know how can this be done.

**Comment by realMAK7** [comment]
In ngOnInit of your TS file, pass whatever text you want to display as follows:
`replaceTexts: {
dragNDropBox: "YOUR TEXT"
}
`
And that's it!

**Comment by candorthor** [comment]
@realMAK7 ,
How can I pass those text like above?
1st row should contain icon
2nd row text
3rs row text

**Comment by kzrfaisal** [comment]
Text can be controlled using 'replaceTexts' config option and CSS classes can also be utilized, but the HTML structure can't be modified.
