### ISSUE TITLE
Styling the progress bar

### ISSUE THREAD

**Issue by Qarun-Qadir-Bissoondial** [kzrfaisal/angular-file-uploader#7]
The progress bar appears to be very very small. Is there any specific ID or class on the progress bar so that i can style it? The upload happens too quickly for me to inspect and it appears that it's hidden on the DOM unless an actual upload is taking place.

**Comment by kzrfaisal** [comment]
Yeah, you can use the class ' .progress > .progress-bar ' . The reason that progress bar disappears quickly is because progress bar shows real-time progress and in your case upload is faster.
