### ISSUE TITLE
Falta un texto por reemplazo

### ISSUE THREAD

**Issue by NinoSoftCo** [kzrfaisal/angular-file-uploader#72]
Excelente herramienta, sin embargo te cuento que para la parte de experiencia de usuario falta un texto por poder reemplazar "Size limit"
![SizeLimit](https://user-images.githubusercontent.com/61243241/74852997-4e340880-530b-11ea-9637-0bd1d62f1035.png)

**Comment by kzrfaisal** [comment]
Muchas gracias, seguramente lo consideraré en el próximo lanzamiento.

**Comment by kzrfaisal** [comment]
Det är tillgängligt i nästa utgåva, som kommer att finnas tillgängligt inom en vecka.
