### ISSUE TITLE
Please support angular 9.0.x

### ISSUE THREAD

**Issue by BruneXX** [kzrfaisal/angular-file-uploader#73]
ERROR in Error when flattening the source-map "/ng-app/node_modules/angular-file-uploader/bundles/angular-file-uploader.umd.js.map" for "/ng-app/node_modules/angular-file-uploader/bundles/angular-file-uploader.umd.js": TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null

**Comment by BruneXX** [comment]
Can you specify full path on karma.conf.js? line 19?
`dir: require('path').join(__dirname, '../coverage'),`

**Comment by kzrfaisal** [comment]
Planning for a latest angular support release soon.

**Comment by BruneXX** [comment]
Thanks!

**Comment by bhavyakaria** [comment]
Hi @kzrfaisal any update on the support for Angular 9?

**Comment by kzrfaisal** [comment]
Hey @bhavyakaria , I'm working on angular 9 support with couple of updates, it will be available within a week on npm, or if you want to see it now it's available under 'new' branch.

**Comment by kzrfaisal** [comment]
Angular file uploader version 6 officially released with the support of Angular 9.
