### ISSUE TITLE
this.fileUpload1.resetFileUpload(); ERROR

### ISSUE THREAD

**Issue by abelnexus** [kzrfaisal/angular-file-uploader#77]
`import { ViewChild } from "@angular/core";
import { AngularFileUploaderComponent } from "angular-file-uploader";
declare var jsPDF: any;

@ViewChild("fileUpload1")
@Component({
  selector: "app-mensual",
  templateUrl: "./mensual.component.html",
  styleUrls: ["./mensual.component.css"],
  providers: [UserService, MensualService, AngularFileUploaderComponent],
})`

`  
constructor(

    private toastr: ToastrService,
    private _userService: UserService,
    private _mensualService: MensualService,
    private _router: Router,
    private fileUpload1: AngularFileUploaderComponent,
    private _route: ActivatedRoute
  )`

`  resetear() {
this.fileUpload1.resetFileUpload();
  }`

`                  
<angular-file-uploader

                    #fileUpload1
                    [config]="afuConfig"
                    [resetUpload]="resetVar"
                    (ApiResponse)="pdfUpload($event)"
                  >
                  
</angular-file-uploader>
`
core.js:6185 ERROR TypeError: Cannot read property 'resetFileUpload' of undefined

**Comment by kzrfaisal** [comment]
Follow the documentation correctly.
   `
 @ViewChild('fileUpload1')
    private fileUpload1: AngularFileUploaderComponent `

**Comment by kzrfaisal** [comment]
Try it like this, according to documentation.
` @ViewChild('fileUpload1')
    private fileUpload1: AngularFileUploaderComponent `
