### ISSUE TITLE
Does it support I18n(other languages)?

### ISSUE THREAD

**Issue by amt123** [kzrfaisal/angular-file-uploader#8]
Hello,

excellent job bro, nicely done but I do have project that will use three languages so is it possiable?
can you tell me how to append my own id with file name uploaded ?

**Comment by kzrfaisal** [comment]
Thanks @amt123 .
Language thing, I haven't tried that, so maybe it can support that. 
However, your second question, can you pls elaborate it.

**Comment by kzrfaisal** [comment]
Right now in npm package this kind of option is not there, but you are free to use github code and modify it,
for appending your id , you can use caption because right now caption is just using default string 'file'.

**Comment by rochapablo** [comment]
Any update about I18n?
