### ISSUE TITLE
Support files of arbitrary type

### ISSUE THREAD

**Issue by natejgardner** [kzrfaisal/angular-file-uploader#80]
It appears there's currently no way to upload files of any type. Many binary files for typical use-cases don't have file extensions. 

The project would benefit from a config option to disable filetype checking entirely.

**Comment by SachaFyson** [comment]
Any updates on this? I'd like to be able to support uploading any kind of text file (I can do content verification myself), because I can't predict the type of file my users will be uploading.

**Comment by kzrfaisal** [comment]
Update:
Version: 7.1.0

- All file type can be supported by using `'*'` in formatAllowed.
- All Image formats can be supported by using `'image/*'` and similarly for video and audio.
