### ISSUE TITLE
Headers Authoritation doesn't send

### ISSUE THREAD

**Issue by bukohub** [kzrfaisal/angular-file-uploader#83]
Hi Friend,

First, thank u for this excelent library. 

Second, when the library execute the API, the headers doesn't works. Authorization is null.
I'm using Angular 9. 

Thank u

**Comment by kzrfaisal** [comment]
Hey @bukohub ,
Can you please share the code how you are sending the headers.

**Comment by kzrfaisal** [comment]
Anyway it has been fixed now in the latest version
