### ISSUE TITLE
HttpClientModule lazy loaded modules

### ISSUE THREAD

**Issue by danielehrhardt** [kzrfaisal/angular-file-uploader#85]
Hi
i want to report a Bug.
When i import your Module into one of my Lazy Loaded Modules my Interceptors does not work anymore.

This is the reason behind:
https://dev.to/devakone/angular-when-httpinterceptor-doesn-t-work-with-lazy-loaded-modules-3ipg

I think you should not import HttpClientModule, because it will create an own instance without the Interceptors. 

Could you fix it?
Best,
Daniel

**Comment by alastair-todd** [comment]
I have just stumbled upon exactly the same issue.

**Comment by danielehrhardt** [comment]
https://github.com/codextde/angular-file-uploader

**Comment by kzrfaisal** [comment]
I have updated the package to version 7.0.3 with a fix mentioned in the article mentioned by @danielehrhardt (Thanks a lot for your effort).
I have used the skipSelf decorator fix mentioned in the comments section.
@alastair-todd You can update the package and try.
If it works, Please close the Issue with a confirmation.

**Comment by danielehrhardt** [comment]
> I have updated the package to version 7.0.3 with a fix mentioned in the article mentioned by @danielehrhardt (Thanks a lot for your effort).
> I have used the skipSelf decorator fix mentioned in the comments section.
> @alastair-todd You can update the package and try.
> If it works, Please close the Issue with a confirmation.

Thank you ♥
