### ISSUE TITLE
Disable upload button during upload

### ISSUE THREAD

**Issue by BruneXX** [kzrfaisal/angular-file-uploader#86]
This is a feature request, will be possible to add an option that disables the button while file is uploading?

**Comment by BruneXX** [comment]
Currently I can make multiple clicks on upload button and a lot of POST api calls are fired.

**Comment by kzrfaisal** [comment]
Select, Reset and Upload Buttons will be disabled when uploading in the next version.

**Comment by kzrfaisal** [comment]
Version 7.1.0 released
