### ISSUE TITLE
Call method before send

### ISSUE THREAD

**Issue by pgrmCreate** [kzrfaisal/angular-file-uploader#88]
For multiples reasons, we can need control the sent event (ex : check global form, use differents buttons for send upload, active upload programmly).

Anyone have found a hack for that ? I think purpose a pull request if this not exist.

(PS : Well job for repo)

**Comment by kzrfaisal** [comment]
Need some more details to know exactly what is the requirement

**Comment by kzrfaisal** [comment]
feel free to open is anytime
