### ISSUE TITLE
(ApiResponse) from html don't send to the method update($event) the image.

### ISSUE THREAD

**Issue by codefaztaz** [kzrfaisal/angular-file-uploader#89]
I can't get the data from angular file uploader from html component to angular 10 .ts component

update(data)
{
  console.log(data); //error TypeError: can't access property "length", values is undefined
}

**Comment by codefaztaz** [comment]
```
           <angular-file-uploader #fileUpload1 [config]="afuConfig" [resetUpload]=resetVar (ApiResponse)="upload($event)">
            </angular-file-uploader>
```
```
upload(img)
{
 // let data = img.response;
//  this.book.image = img.response;
 // console.log(this.book.image);
  console.log(img);
}
```

**Comment by kzrfaisal** [comment]
Here's an example for your usecase:

https://stackblitz.com/edit/angular-ivy-o8txpq?file=src/app/app.component.ts

**Comment by codefaztaz** [comment]
thank you mate
