### ISSUE TITLE
how to send params id in afuconfig to update an item in the backend?

### ISSUE THREAD

**Issue by codefaztaz** [kzrfaisal/angular-file-uploader#90]
afuConfig: AngularFileUploaderConfig = {

  multiple: false,
  formatsAllowed: '.jpg, .jpeg, .png, .gif',
 // maxSize: '50' ,
  uploadAPI:{
    url: 'http://localhost:3999/admin/' + 'upload-avatar',
   //url:'https://slack.com/api/files.upload',
    method: 'PUT',
   
    // headers: { 'Content-Type': 'multipart/form-data boundary=???' },
   // headers:{
  //  'Authorization': this.token,
   // 'Content-Type': 'multipart/form-data boundary=???'
   // }
    
  },

  params: { 'id': this.book.id }, // error cant not read property id
  

  theme: 'attachPin',
  hideProgressBar: false,
  hideResetBtn: true,
  hideSelectBtn: false,
 // attachPinText: ' Sube la imagen'
};

I need to send an id to the backend but I dont know......

**Comment by kzrfaisal** [comment]
I guess the error is related to `this.book.id`, 
anyway  here's an example for your use case:
https://stackblitz.com/edit/angular-ivy-o8txpq?file=src%2Fapp%2Fapp.component.ts

**Comment by codefaztaz** [comment]
in the example the purchase_id: "1" but how to get the current id book in afuconfig?

**Comment by kzrfaisal** [comment]
purchase_id is just name of the param, getting the current book id is not the part of this library mate, id does not exist on this.book object, kindly debug your code.
