### ISSUE TITLE
maxSize does not appear to filter pdfs in the dialog in an ionic/angular app

### ISSUE THREAD

**Issue by leonsegal** [kzrfaisal/angular-file-uploader#92]
All pdfs appear in the dialog, no matter how l set the maxSize. l haven't tested for other file types

**Comment by kzrfaisal** [comment]
Hi @leonsegal ,
Need some more details.
Do you mean it's not getting filtered just as shown in the below Image or in the File Selection Dialog that appears when you click on `Select File`.

![image](https://user-images.githubusercontent.com/13894812/101632931-9106ce80-3a4c-11eb-871d-6d8b05ffa6fb.png)

**Comment by leonsegal** [comment]
In the actual dialog itself, l have been reading around though and it looks like that is a browser limitation. lf so maybe we can close this issue.

**Comment by kzrfaisal** [comment]
Yep, this limitation takes effect after File Select and before Upload.
