### ISSUE TITLE
how to upload more than one image and send to the backend a identifier of each image

### ISSUE THREAD

**Issue by codefaztaz** [kzrfaisal/angular-file-uploader#93]
I am uploading 5 images 
```
   <angular-file-uploader [config]="afuConfig" (ApiResponse)="upload1($event)">
                    </angular-file-uploader>

 <angular-file-uploader [config]="afuConfig2 " (ApiResponse)="upload2($event) ">
                    </angular-file-uploader>


how to know in nodejs wich image is image1 (afuConfig) or image2 (afuConfig2) how to send diferent file data images with the library 

I need to refactor nodejs function but I dont know how to diference each image from Angular

```

**Comment by kzrfaisal** [comment]
You can add params to the api from afuConfig. Refer example 2 in the documentation.
You can do something like this.
afuConfig.uploadAPI.params = { 'imgFrom': '1' };
afu2Config.uploadAPI.params = { 'imgFrom': '2' };

And check for these params at the backend to identify the image source.

**Comment by codefaztaz** [comment]
how to get the value of params??
```
 var afuimage = req.params.image;?

afuConfig: AngularFileUploaderConfig = {
            
            multiple: false,
            formatsAllowed: '.jpg, .jpeg, .png, .gif',
            // maxSize: '50' ,
            uploadAPI:{
              url: 'http://localhost:3999/admin/' + 'upload-avatar',
              
              params: {
                'image': '1'
              }
              // headers:{
              //'Authorization': this.token,
              
              // }
              
            },
```

**Comment by kzrfaisal** [comment]
In you api handler function at your backend, where you are getting the image, you will get params also,
You need to explore docs (depending on the framework that you are using) to how to get params from request object.


I need to close this issue because the next steps are not related to this library

**Comment by codefaztaz** [comment]
I get the object image in my backend I can upload the image but I dont get the params 'image' I am using nodejs with mongodb and express

**Comment by kzrfaisal** [comment]
According to express documentation you need to use `req.query.image` in order to get them and you can also explore devtools network tab to see whether your query params has been sent or not.

**Comment by codefaztaz** [comment]
thank you Faisal req.query.image works problem fixed next time I will check before the documentation 
thank you very much
